name: Docker Image CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:     
  build_test_push:
    name: build_test_push
    permissions: write-all
    runs-on: ubuntu-latest 
    env:
      DOCKER_REPOSITORY: kennethfoo24 # name of Docker Hub ID
      IMAGE_NAME: python-security
      
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v5.0.0   

    - name: Check code meets quality standards
      id: datadog-static-analysis
      uses: DataDog/datadog-static-analyzer-github-action@v1
      with:
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_service: cloudrun-python-security
        dd_env: cloudrun-python 
        cpu_count: 2
        enable_performance_statistics: true

    - name: Check imported libraries are secure and compliant (DD SBOM Generate and Upload)
      id: datadog-software-composition-analysis
      uses: DataDog/datadog-sca-github-action@main
      with:
        dd_api_key: ${{ secrets.DD_API_KEY }}
        dd_app_key: ${{ secrets.DD_APP_KEY }}
        dd_service: cloudrun-python-security
        dd_env: cloudrun-python
        dd_site: datadoghq.com
          
    - name: Build Docker Image 
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}
        registry: docker.io
        tag: latest
        buildArgs: 'DD_GIT_REPOSITORY_URL=github.com/jon94/fargatepythonbackend,DD_GIT_COMMIT_SHA=$(git rev-parse HEAD)'
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Datadog Service Catalog Metadata Provider
      uses: arcxp/datadog-service-catalog-metadata-provider@v2.1.0
      with:
        # The Datadog API hostname (this varies by Datadog customer!)
        datadog-hostname: api.datadoghq.com
        # The Datadog API key, add this as repo secret
        datadog-key: ${{secrets.DD_API_KEY}}
        # The Datadog Application key, add this as repo secret
        datadog-app-key: ${{secrets.DD_APP_KEY}}
        # The version of the Datadog Service Catalog Schema. The default is v2. Valid values are `v2` and `v2.1`.
        schema-version: v2
        # The name of the service
        service-name: cloudrun-python-security, postrequest
        # The team responsible for the service
        team: SRE
        # The email address of the team responsible for the service
        email: kenneth.foo@datadoghq.com


          
